/**
 * Google Fonts faces for the curated terminal themes.
 *
 * The module deliberately ships no font binaries: these families are declared
 * against Google's CDN and registered into CONFIG.fontDefinitions, so Foundry
 * loads them itself and also lists them in its own font pickers.
 *
 * Two consequences worth knowing about: a world with no internet access falls
 * back to the CSS `monospace` chain, and each player's IP address reaches
 * Google when the faces load.
 *
 * Generated by scripts/dev/refresh-google-fonts.mjs — do not edit by hand.
 */
export const GOOGLE_FONT_DEFINITIONS = Object.freeze({
  "VT323": {
    editor: true,
    fonts: [
      { urls: ["https://fonts.gstatic.com/s/vt323/v18/pxiKyp0ihIEF2isfFJU.woff2"], weight: "400" }
    ]
  },
  "Share Tech Mono": {
    editor: true,
    fonts: [
      { urls: ["https://fonts.gstatic.com/s/sharetechmono/v16/J7aHnp1uDWRBEqV98dVQztYldFcLowEF.woff2"], weight: "400" }
    ]
  },
  "IBM Plex Mono": {
    editor: true,
    fonts: [
      { urls: ["https://fonts.gstatic.com/s/ibmplexmono/v20/-F63fjptAgt5VM-kVkqdyU8n1i8q1w.woff2"], weight: "400" },
      { urls: ["https://fonts.gstatic.com/s/ibmplexmono/v20/-F6qfjptAgt5VM-kVkqdyU8n3pQPwlBFgg.woff2"], weight: "700" }
    ]
  },
  "Space Mono": {
    editor: true,
    fonts: [
      { urls: ["https://fonts.gstatic.com/s/spacemono/v17/i7dPIFZifjKcF5UAWdDRYEF8RQ.woff2"], weight: "400" },
      { urls: ["https://fonts.gstatic.com/s/spacemono/v17/i7dMIFZifjKcF5UAWdDRaPpZUFWaHg.woff2"], weight: "700" }
    ]
  },
  "Courier Prime": {
    editor: true,
    fonts: [
      { urls: ["https://fonts.gstatic.com/s/courierprime/v11/u-450q2lgwslOqpF_6gQ8kELawFpWg.woff2"], weight: "400" },
      { urls: ["https://fonts.gstatic.com/s/courierprime/v11/u-4k0q2lgwslOqpF_6gQ8kELY7pMT-Dfqw.woff2"], weight: "700" }
    ]
  },
  "Oxanium": {
    editor: true,
    fonts: [
      { urls: ["https://fonts.gstatic.com/s/oxanium/v21/RrQQboN_4yJ0JmiMe2LE0Q.woff2"], weight: "400 700" }
    ]
  },
  "Rajdhani": {
    editor: true,
    fonts: [
      { urls: ["https://fonts.gstatic.com/s/rajdhani/v17/LDIxapCSOBg7S-QT7p4HM-Y.woff2"], weight: "400" },
      { urls: ["https://fonts.gstatic.com/s/rajdhani/v17/LDI2apCSOBg7S-QT7pa8FvOreec.woff2"], weight: "700" }
    ]
  },
  "Chakra Petch": {
    editor: true,
    fonts: [
      { urls: ["https://fonts.gstatic.com/s/chakrapetch/v13/cIf6MapbsEk7TDLdtEz1BwkWn6pg.woff2"], weight: "400" },
      { urls: ["https://fonts.gstatic.com/s/chakrapetch/v13/cIflMapbsEk7TDLdtEz1BwkeJI91R5_F.woff2"], weight: "700" }
    ]
  },
  "Roboto Mono": {
    editor: true,
    fonts: [
      { urls: ["https://fonts.gstatic.com/s/robotomono/v31/L0x5DF4xlVMF-BfR8bXMIjhLq38.woff2"], weight: "400 700" }
    ]
  },
  "Source Code Pro": {
    editor: true,
    fonts: [
      { urls: ["https://fonts.gstatic.com/s/sourcecodepro/v31/HI_SiYsKILxRpg3hIP6sJ7fM7PqlPevW.woff2"], weight: "400 700" }
    ]
  }
});
